# specify which database and adapter to use for which environment

development:
  adapter: sqlite3
  database: db/film-file-development

test:
  adapter: sqlite3
  database: db/film-file-test

production:
  adapter: sqlite3
  database: db/film-file-production
